/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package text;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author T-107
 */
public class PresentacionTest extends javax.swing.JFrame {

    /**
     * Creates new form PresentacionTest
     */
    JRadioButton radios[];
    Opcion[]opciones;
    Pregunta p1;
    
    public PresentacionTest() {
        initComponents();
        setLocationRelativeTo(this);
        
        //generar un arregle los radios button visuales 
        
        radios=new JRadioButton[5];
        opciones = new Opcion[5];
        radios[0]=radioOp1;
        radios[1]=radioOp2;
        radios[2]=radioOp3;
        radios[3]=radioOp4;
        radios[4]=radioOp5;
        
        //llenamos el modelo con los valores correctos en la interfaz de usuario 
       
        Opcion op1=new Opcion("las quesadillas  ",false); //el constructor se llama igual que la clase
         Opcion op2=new Opcion("la grasa",false);
         Opcion op3=new Opcion("el azucar ",true);
         Opcion op4=new Opcion("la contaminacion",false);
         Opcion op5=new Opcion("la sal",false);
         
       opciones[0]=op1;
       opciones[1]=op2;
       opciones[2]=op3;
       opciones[3]=op4;
       opciones[4]=op5;
       
         
        p1=new Pregunta("esta es la principall causa del cancer",opciones);
         etiquetaTitulo.setText(p1.titulo);
         for(int i=0;i<radios.length;i++){
             radios[i].setText(p1.opciones[i].titulo);         
             
         }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        etiquetaTitulo = new javax.swing.JLabel();
        radioOp1 = new javax.swing.JRadioButton();
        radioOp2 = new javax.swing.JRadioButton();
        radioOp3 = new javax.swing.JRadioButton();
        radioOp4 = new javax.swing.JRadioButton();
        radioOp5 = new javax.swing.JRadioButton();
        checarrespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaTitulo.setText("jLabel1");

        buttonGroup1.add(radioOp1);
        radioOp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioOp1.setText("jRadioButton1");

        buttonGroup1.add(radioOp2);
        radioOp2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioOp2.setText("jRadioButton2");

        buttonGroup1.add(radioOp3);
        radioOp3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioOp3.setText("jRadioButton3");

        buttonGroup1.add(radioOp4);
        radioOp4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioOp4.setText("jRadioButton4");

        buttonGroup1.add(radioOp5);
        radioOp5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioOp5.setText("jRadioButton5");

        checarrespuesta.setText("VERIFICAR RESPUESTA");
        checarrespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checarrespuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(etiquetaTitulo))
                    .addComponent(radioOp3)
                    .addComponent(radioOp1)
                    .addComponent(radioOp4)
                    .addComponent(radioOp5)
                    .addComponent(radioOp2))
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(checarrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(etiquetaTitulo)
                .addGap(31, 31, 31)
                .addComponent(radioOp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioOp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOp4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOp5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checarrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checarrespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarrespuestaActionPerformed
        // TODO add your handling code here:
        //buscamos el radioButton seleccionado
        int indiceSeleccionado=0;
        for(int i=0;i<radios.length;i++){
            if (radios[i].isSelected()){
                indiceSeleccionado=i;
                break;
            }
        }
        JOptionPane.showConfirmDialog(this,""+ evaluar(p1,radios[indiceSeleccionado])) ;
    }//GEN-LAST:event_checarrespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresentacionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresentacionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresentacionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentacionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresentacionTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checarrespuesta;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JRadioButton radioOp1;
    private javax.swing.JRadioButton radioOp2;
    private javax.swing.JRadioButton radioOp3;
    private javax.swing.JRadioButton radioOp4;
    private javax.swing.JRadioButton radioOp5;
    // End of variables declaration//GEN-END:variables

public boolean evaluar(Pregunta p,JRadioButton r){
    boolean correcta =fal
    for(int i=0;i<p.opciones.length;)
        if (p1.opciones[i].titulo.equals(r.getText())){
            if(p1.opciones[i].correcta){
            correcta=true;
            break;
        }
        }
}
    




